config/routes.rb
Rails.application.routes.draw do

  resources :chats, only: [:index, :new, :show, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
 end
  root 'tops#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :content, presence: true,length: { in: 1..140 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  #
   ## GET /chats/1.json
  def show
  end

  #GET /chats/new
  def new
    @chats = Chat.all
    @chat = Chat.new
    if params[:back]
     @chat = Chat.new(chat_params)
   else
     @chat = Chat.new
   end
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'つぶやき完了' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: '更新完了！' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'ちゃんと削除できました！' }
      format.json { head :no_content }
    end
  end

  def confirm
      @chats = Chat.all
    @chat = Chat.new(chat_params)
    render :new if @chat.invalid?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:content)
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_chats_path
    elsif action_name == 'edit'
      chat_path
    end
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: chat, local: true,url: choose_new_or_edit) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= chat.errors.count%> 件のエラーが発生してるよ</h2>

      <ul>
      <% chat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :つぶやく %>
    <p>１４０字までオーケー</p>
    <%= form.text_area :content, id: :chat_content %>
  </div>

  <div class="actions">
    <%= form.submit'Go!',class: 'btn btn-default btn-sm btn-success'%>
  </div>
<% end %>

app/views/chats/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@chat) do |f| %>
  <%= f.hidden_field :content %>

  <p>本文:<%= @chat.content %></p>
  <%= f.submit "登録する",class: 'btn btn-default btn-sm btn-success'%>
<% end %>
<%= form_for(@chat, url: new_chat_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back',class: 'btn btn-default' %>
<% end %>

app/views/chats/edit.html.erb
<h1>つぶやきを編集する？</h1>

<%= render 'form', chat: @chat %>
<%= link_to '戻る', root_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

<br>
<table>
   <tbody>
    <div class="container">
     <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
      <h1>つぶやき一覧</h1>
      <% @chats.each do |chat| %>
      <div class="row">
        <%= chat.content %>
        <div class="row2">
        <%= link_to "編集", edit_chat_path(chat), class: 'btn btn-default btn-sm btn-success' %>
        <%= link_to "削除",chat, method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
       </div>
      </div>
      <% end %>
    </div>
    </div>
   </tbody>
</table>

app/views/chats/new.html.erb
<section class="top">
<p id="notice"><%= notice %></p>
<h1>twitter</h1>
</section>
<%= render 'form', chat: @chat %>
  
<!--<br>
<%= link_to '戻る', chats_path ,class:'btn btn-default btn-sm btn-success'%>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>内容:</strong>
  <%= @chat.content %>
</p>

<%= link_to '編集', edit_chat_path(@chat),class: 'btn btn-default btn-sm btn-success' %>
<br>
<%= link_to "つぶやき一覧", chats_url %>
<br>
<%= link_to 'トップページ', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
     <header>
      <ul>
       <li><a href="/">トップページ</a></li>
      <section class="navbar-right">
        <li><%= link_to "つぶやき一覧", chats_url %></li>
        <li><%= link_to '新規投稿',  new_chat_url%></li>
      </section>
      </ul>
    </header>
    <footer>
     <p>Dive into code 課題７</p>
    </footer>
     <%= yield %>
  </body>
</html>

app/views/tops/index.html.erb
<p id="notice"><%= notice %></p>
<section class="about">
  <h1>Twitter</h1>
  <p>
     Twitterは、Dive into Codeの課題として作成されました。<br>
     好きなことをコメントできます。日頃、心にしまっていることや、イラっときたことを呟いちゃおう。
     運営元は華麗にシカトします。
  </p>
  <p>
     さぁ、呟いちゃいますか<br>
     <%= link_to "つぶやく", new_chat_path, class: 'btn btn-default btn-sm btn-success' %>
  </p>
</section>